export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const SET_ACTIVE_LIST = "SET_ACTIVE_LIST";
export const CREATE_QUESTION = "CREATE_QUESTION";
export const SAVE_QUESTION_ANSWER = "SAVE_QUESTION_ANSWER";
export const SET_RES_OR_QUESTION = "SET_RES_OR_QUESTION";




